// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectSim.DataAccess;

#nullable disable

namespace ObjectSim.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250616172010_addAttribute")]
    partial class addAttribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObjectSim.Domain.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("DataTypeId");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DataTypeId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IsStatic = false,
                            Name = "default",
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("ObjectSim.Domain.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsAbstract")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInterface")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = false,
                            Name = "Object"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "String",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Int32",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Boolean",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Char",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Decimal",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Byte",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "float",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            IsAbstract = false,
                            IsInterface = false,
                            IsSealed = true,
                            Name = "Double",
                            ParentId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ObjectSim.Domain.DataType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataTypes");

                    b.HasDiscriminator().HasValue("DataType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ObjectSim.Domain.InvokeMethod", b =>
                {
                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvokeMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MethodId", "InvokeMethodId");

                    b.ToTable("InvokeMethod");
                });

            modelBuilder.Entity("ObjectSim.Domain.Key", b =>
                {
                    b.Property<Guid>("AccessKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessKey");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            AccessKey = new Guid("9c0ff0b1-4abd-45c6-8a4a-831748fb7a20")
                        },
                        new
                        {
                            AccessKey = new Guid("515dd649-30a0-4d57-9302-62a8db8179bd")
                        });
                });

            modelBuilder.Entity("ObjectSim.Domain.Method", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Abstract")
                        .HasColumnType("bit");

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("Methods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Equals",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Equals (Object, Object)",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Abstract = false,
                            Accessibility = 2,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Finalize",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "GetHashCode",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "GetType",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Abstract = false,
                            Accessibility = 2,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "MemberwiseClone",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "ReferenceEquals",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            Abstract = false,
                            Accessibility = 0,
                            ClassId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsOverride = false,
                            IsSealed = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "ToString",
                            TypeId = new Guid("00000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("ObjectSim.Domain.Namespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassIdsSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClassIdsSerialized");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Namespaces");
                });

            modelBuilder.Entity("ObjectSim.Domain.Variable", b =>
                {
                    b.Property<Guid>("VariableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VariableId");

                    b.HasIndex("MethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("ObjectSim.Domain.ReferenceType", b =>
                {
                    b.HasBaseType("ObjectSim.Domain.DataType");

                    b.HasDiscriminator().HasValue("ReferenceType");
                });

            modelBuilder.Entity("ObjectSim.Domain.ValueType", b =>
                {
                    b.HasBaseType("ObjectSim.Domain.DataType");

                    b.HasDiscriminator().HasValue("ValueType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Type = "void"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Type = "int"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Type = "bool"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Type = "char"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Type = "decimal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Type = "byte"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Type = "float"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Type = "double"
                        });
                });

            modelBuilder.Entity("ObjectSim.Domain.Attribute", b =>
                {
                    b.HasOne("ObjectSim.Domain.Class", null)
                        .WithMany("Attributes")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectSim.Domain.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("ObjectSim.Domain.Class", b =>
                {
                    b.HasOne("ObjectSim.Domain.Class", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ObjectSim.Domain.InvokeMethod", b =>
                {
                    b.HasOne("ObjectSim.Domain.Method", null)
                        .WithMany("MethodsInvoke")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectSim.Domain.Method", b =>
                {
                    b.HasOne("ObjectSim.Domain.Class", null)
                        .WithMany("Methods")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectSim.Domain.DataType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectSim.Domain.Namespace", b =>
                {
                    b.HasOne("ObjectSim.Domain.Namespace", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ObjectSim.Domain.Variable", b =>
                {
                    b.HasOne("ObjectSim.Domain.Method", null)
                        .WithMany("Parameters")
                        .HasForeignKey("MethodId");

                    b.HasOne("ObjectSim.Domain.DataType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObjectSim.Domain.Method", null)
                        .WithMany("LocalVariables")
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObjectSim.Domain.Class", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("ObjectSim.Domain.Method", b =>
                {
                    b.Navigation("LocalVariables");

                    b.Navigation("MethodsInvoke");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ObjectSim.Domain.Namespace", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
